<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Instructions" data-toc-modified-id="Instructions-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Instructions</a></span></li><li><span><a href="#Before-You-Begin" data-toc-modified-id="Before-You-Begin-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Before You Begin</a></span></li><li><span><a href="#Imports" data-toc-modified-id="Imports-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Imports</a></span></li><li><span><a href="#Questions" data-toc-modified-id="Questions-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Questions</a></span><ul class="toc-item"><li><span><a href="#$\LaTeX$-Typesetting" data-toc-modified-id="$\LaTeX$-Typesetting-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>$\LaTeX$ Typesetting</a></span><ul class="toc-item"><li><span><a href="#Typeset-a-Constrained-Linear-Optimization-Problem" data-toc-modified-id="Typeset-a-Constrained-Linear-Optimization-Problem-4.1.1"><span class="toc-item-num">4.1.1&nbsp;&nbsp;</span>Typeset a Constrained Linear Optimization Problem</a></span></li><li><span><a href="#Typeset-a-Constrained-Quadratic-Optimization-Problem" data-toc-modified-id="Typeset-a-Constrained-Quadratic-Optimization-Problem-4.1.2"><span class="toc-item-num">4.1.2&nbsp;&nbsp;</span>Typeset a Constrained Quadratic Optimization Problem</a></span></li></ul></li><li><span><a href="#CVXPY" data-toc-modified-id="CVXPY-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>CVXPY</a></span><ul class="toc-item"><li><span><a href="#Linear-Optimization" data-toc-modified-id="Linear-Optimization-4.2.1"><span class="toc-item-num">4.2.1&nbsp;&nbsp;</span>Linear Optimization</a></span></li><li><span><a href="#Linear-Optimization" data-toc-modified-id="Linear-Optimization-4.2.2"><span class="toc-item-num">4.2.2&nbsp;&nbsp;</span>Linear Optimization</a></span></li><li><span><a href="#Quadratic-Optimization" data-toc-modified-id="Quadratic-Optimization-4.2.3"><span class="toc-item-num">4.2.3&nbsp;&nbsp;</span>Quadratic Optimization</a></span></li><li><span><a href="#Quadratic-Optimization" data-toc-modified-id="Quadratic-Optimization-4.2.4"><span class="toc-item-num">4.2.4&nbsp;&nbsp;</span>Quadratic Optimization</a></span></li></ul></li><li><span><a href="#Optimal-Advertising-Plan" data-toc-modified-id="Optimal-Advertising-Plan-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Optimal Advertising Plan</a></span><ul class="toc-item"><li><span><a href="#Decision-Variables" data-toc-modified-id="Decision-Variables-4.3.1"><span class="toc-item-num">4.3.1&nbsp;&nbsp;</span>Decision Variables</a></span></li><li><span><a href="#Objective" data-toc-modified-id="Objective-4.3.2"><span class="toc-item-num">4.3.2&nbsp;&nbsp;</span>Objective</a></span></li><li><span><a href="#Constraints" data-toc-modified-id="Constraints-4.3.3"><span class="toc-item-num">4.3.3&nbsp;&nbsp;</span>Constraints</a></span></li><li><span><a href="#Solution" data-toc-modified-id="Solution-4.3.4"><span class="toc-item-num">4.3.4&nbsp;&nbsp;</span>Solution</a></span></li></ul></li></ul></li></ul></div>

<h1>Instructions</h1>
<br>
<font size="+1">
    <ul>
        <li style="color:red">This problem set assesses your ability to analyze a given business decision by creating a concrete formulation of an optimization model, as well as practice solving your optimizaton model with CVXPY and summarizing the results. You should typeset math within Markdown using $\LaTeX$.</li>
        <br>
        <li><b>Recommended Steps</b></li>
        <br>
        <ol>
            <li>Read the prompt and summarize the task in your own words, using as few words as possible for ease of comprehension.</li>
            <br>
            <li>Pretend to be the computer program that you are trying to create. Examine the sample inputs and manually produce the appropriate results. Afterward, verify the correctness of your logic by comparing with the given sample outputs.</li>
            <br>
            <li>On a scrap piece of paper, write step-by-step instructions so that someone else can pretend to be the computer program and produce the appropriate results for any possible inputs. These instructions should target a human audience who does not know the problem description and only has your instructions as a guide. These instructions should serve as the roadmap for your code.</li>
            <br>
            <li>On another scrap piece of paper, write fragments of Python code to implement each step in your roadmap, focusing especially on the trickiest parts of the logic.</li>
            <br>
            <li>With your roadmap and code fragments from the previous steps, type Python code into a new Jupyter notebook cell to solve the given problem. You should type incrementally and run the code whenever you add a small chunk. This allows you to correct errors as they occur. It may also be helpful to print intermediate results to verify that the code is carrying out the logic as desired.</li>
            <br>
            <li>Run your code with some sample inputs and verify that the outputs are exactly the same as the sample outputs.</li>
            <br>
            <li>Once all of your problems are finished, it is useful to click <i>Kernel</i> $\rightarrow$ <i>Restart & Run All</i> to verify that your outputs for all of your problems continue to be correct. This helps to ensure that someone else will be able to replicate your results when running your notebook.</li>
            <br>
            <li style="color:red">Submit the <i>.ipynb</i> file on TurnItIn on Blackboard by the deadline. Be sure to refresh the page and double check your submission actually went through. <b>Note that you only need to submit your solutions, not all of the other recommended steps.</b> The recommended steps are meant to serve as a guide for your thinking process.</li>
            <br>
        </ol>
        <br>
        <hr style="border: 10px solid black">
        <br>
        <li><b>Grading</b></li>
        <br>
        <li>There are four possible scores you can get from submitting this assignment on time (submitting a blank file or one without any apparent effort does not count). Note that the rubric is designed to incentivize you to go for $100%$ mastery of the material, as the little details matter in programming.</li>
        <br>
        <ul>
            <li>Grade of $5$ out of $5$ - perfect submission with no significant errors</li>
            <br>
            <li>Grade of $4$ out of $5$ - near perfect submission with one or more significant errors</li>
            <br>
            <li>Grade of $2$ out of $5$ - apparent effort but far from perfect</li>
            <br>
            <li>Grade of $0$ out of $5$ - no submission or no apparent effort</li>
            <br>
        </ul>
    </ul>
</font>

<hr style="border: 20px solid black">

<h1>Before You Begin</h1>
<br>
<font size="+1">
    <ul>
        <li>Please read: <b>01_Intro_to_Optimization_The_Business_of_Banking_Formulation.ipynb</b></li>
        <br>
        <li>Please read: <b>02_Intro_to_CVXPY.ipynb</b></li>
        <br>
        <li>Please read: <b>03_Intro_to_Optimization_The_Business_of_Banking_and_CVXPY.ipynb</b></li>
        <br>
        <li>Please read: <b>AUXILLARY_Typesetting_Math_with_LaTeX.ipynb</b></li>
        <br>
    </ul>
</font>

<hr style="border: 20px solid black">

<h1>Imports</h1>
<br>
<font size="+1">
    <ul>
        <li>Put your imports below.</li>
        <br>
        <li>Import Numpy and Pandas</li>
        <br>
    </ul>
</font>

In [1]:
import numpy as np
import pandas as pd

<hr style="border: 20px solid black">

<h1>Questions</h1>

<h2>$\LaTeX$ Typesetting</h2>
<br>
<h3>Typeset a Constrained Linear Optimization Problem</h3>
<br>
<font size="+1">
    <ul>
        <li>Use $\LaTeX$ to format the following constrained optimization problem.</li>
        <br>
        <li>Be sure equations are aligned, you can choose the specific alignment.</li>
        <br>
    </ul>
</font>
<br>
<br>
<img src="https://d2vlcm61l7u1fs.cloudfront.net/media%2F94c%2F94c630eb-9872-4594-8944-3f09f8ea2182%2Fphpw5gPgE.png">

$$\begin{align}
\text{ maximize: } & 20x_1 + 15x_2 & \\ \\
\text{ subject to: } & 4x_1 + 2x_2 & \leq 50 \\
& 2x_1 + 8x_2 & \leq 35 \\
& x_1 & \geq 0 \\
& x_2 & \geq 0 \\
\end{align}$$

<br>
<h3>Typeset a Constrained Quadratic Optimization Problem</h3>
<br>
<font size="+1">
    <ul>
        <li>Use $\LaTeX$ to format the following constrained optimization problem.</li>
        <br>
        <li>Note this is a <b>quadratic</b> optimization problem since some of the decision variables are squared and multiplied together, these are called cross-terms.</li>
        <br>
        <li>Be sure equations are aligned, you can choose the specific alignment.</li>
        <br>
    </ul>
</font>
<br>
<br>
<img src="https://miro.medium.com/max/1348/1*FPIP1_Nmmmf46vewAYkh4Q.png">

$$\begin{align}
\text{ minimize: } & 3x_1^2 + 4x_2^2 + 2x_1x_2 + 5x_1 + x_2 & \\ \\
\text{ subject to: } & x_1 & \geq 0 \\
& x_2  & \geq 0 \\
& x_1 + 2x_2 & = 1 \\
\end{align}$$


<h2>CVXPY</h2>
<br>
<font size="+1">
    <ul>
        <li>For the following problems, the goal is to practice CVXPY syntax, rather than any particulars about modeling.</li>
        <br>
    </ul>
</font>

In [2]:
import cvxpy as cp

<h3>Linear Optimization</h3>
<br>
<font size="+1">
    <ul>
        <li>What is the optimal solution for the following two variable linear optimization problem?</li>
        <br>
        <li>$$\begin{align}
        \text{maximize: } & 2x_1 - x_2 \\ \\
        \text{subject to: } & x_1 + x_2 & \geq 1 \\
        & x_1 - x_2  & \leq 0 \\
        & 3x_1 + x_2 & \leq 6 \\
        & x_1, x_2 \geq 0 \\ \end{align}$$</li>
        <br>
    </ul>
</font>

In [3]:
x = cp.Variable(2)

In [4]:
g= 2*x[0]-x[1]

objective = cp.Maximize(g)

In [5]:
f_1 = (x[0] + x[1] >=1)

f_2 = (x[0] - x[1] <=0)

f_3 =  (3 * x[0]+ x[1] <=6)

f_4 =  (x >=0)

In [6]:
prob = cp.Problem(objective, [f_1, f_2, f_3, f_4])

In [7]:
prob.solve()

1.500000000002468

In [8]:
x.value

array([1.5, 1.5])

<h3>Linear Optimization</h3>
<br>
<font size="+1">
    <ul>
        <li>What is the optimal solution for the following two variable linear optimization problem?</li>
        <br>
        <li>$$\begin{align}
        \text{maximize: } & 2x_1 + 3x_2 \\ \\
        \text{subject to: } & x_1 + x_2 & \leq 5 \\
        & x_1  & \geq 1 \\
        & x_2 & \geq 2 \\ \end{align}$$</li>
        <br>
    </ul>
</font>

In [9]:
x = cp.Variable(2)

In [10]:
g= 2*x[0] + 3*x[1]

objective = cp.Maximize(g)

In [11]:
f_1 = (x[0] + x[1] <=5)

f_2 = (x[0] >=1)

f_3 =  (x[1]>=2)

In [12]:
prob = cp.Problem(objective, [f_1, f_2, f_3])

In [13]:
prob.solve()

13.999999988444877

In [14]:
x.value

array([1.00000001, 3.99999999])

<h3>Quadratic Optimization</h3>
<br>
<font size="+1">
    <ul>
        <li>What is the optimal solution for the following two variable <b>quadratic</b> optimization problem?</li>
        <br>
        <li>Note this is a quadratic optimization problem since some of the decision variables are squared.</li>
        <br>
        <li>$$
\begin{align}
\text{minimize: } & 3x_1^2 + 4x_2^2 + 5x_1 + x_2 \\ \\ 
\text{subject to: } & x_1 & \geq 0 \\
& x_2 & \geq 0 \\
& x_1 + x_2 & = 1 \\
\end{align}
$$</li>
        <br>
    </ul>
</font>

In [15]:
x = cp.Variable(2)

In [16]:
g= 3*x[0]**2 + 4*x[1]**2 + 5*x[0] + x[1]

objective = cp.Minimize(g)

In [17]:
f_1 = (x[0] >=0)

f_2 = (x[1] >=0)

f_3 =  (x[0] + x[1] == 1)

In [18]:
prob = cp.Problem(objective, [f_1, f_2, f_3])

In [19]:
prob.solve()

4.428571428571429

In [20]:
x.value

array([0.28571429, 0.71428571])

<h3>Quadratic Optimization</h3>
<br>
<font size="+1">
    <ul>
        <li>What is the optimal solution for the following two variable <b>quadratic</b> optimization problem?</li>
        <br>
        <li>Note this is a quadratic optimization problem since some of the decision variables are squared.</li>
        <br>
        <li>$$
\begin{align}
\text{minimize: } & 0.4x_1^2 - 5x_1 + x_2^2 - 6x_2 + 50 \\ \\ 
\text{subject to: } & x_1 - x_2 & \geq 2 \\
& 0.3x_1 + x_2 & \geq 8 \\
& x_1, x_2 & \geq 0 \\
& x_1, x_2 & \leq 10 \\
\end{align}
$$</li>
        <br>
    </ul>
</font>

In [21]:
x = cp.Variable(2)

In [22]:
g= 0.4*x[0]**2 - 5*x[0] + x[1]**2 - 6*x[1] + 50

objective = cp.Minimize(g)

In [23]:
f_1 = (x[0] - x[1] >= 2)

f_2 = (0.3*x[0] + x[1] >= 8)

f_3 =  (x >= 0)

f_4 = (x <= 10)

In [24]:
prob = cp.Problem(objective, [f_1, f_2, f_3])

In [25]:
prob.solve()

33.34693877551021

In [26]:
x.value

array([8.16326531, 5.55102041])

<h2>Optimal Advertising Plan</h2>
<br>
<font size="+1">
    <ul>
        <li>SALS Marketing Inc. is developing an advertising campaign for a large consumer goods corporation.</li>
        <br>
        <li><b>An advertising plan specifies how many units of each kind of advertisement to purchase.</b></li>
        <br>
        <li>SALS has promised a plan that will yield the highest possible <i>exposure rating</i>, which is a measure of the ability to reach the appropriate demographic group and generate demand.</li>
        <br>
        <li>The options for advertisements with their respective costs (per-unit of advertising) and per-unit exposure ratings are given in the following table ($K$ stands for thousands):</li>
        <br>
        <li><table>
  <tr>
    <th>Category</th>
    <th>Subcategory</th>
      <th>Cost / Unit</th>
      <th>Exposure / Unit</th>
  </tr>
  <tr>
    <td>Magazines</td>
    <td>Literary</td>
      <td>$\$7.5 K$</td>
      <td>$15 K$</td>
  </tr>
    <tr>
    <td></td>
    <td>News</td>
      <td>$\$10 K$</td>
      <td>$22.5 K$</td>
  </tr>
              <tr>
    <td></td>
    <td>Topical</td>
      <td>$\$15 K$</td>
      <td>$24 K$</td>
  </tr>
  <tr>
    <td>Newspapers</td>
    <td>Morning</td>
      <td>$\$2 K$</td>
      <td>$37.5 K$</td>
  </tr>
    <tr>
    <td></td>
    <td>Evening</td>
      <td>$\$3 K$</td>
      <td>$75 K$</td>
  </tr>
  <tr>
    <td>Television</td>
    <td>Morning</td>
      <td>$\$20 K$</td>
      <td>$275 K$</td>
  </tr>
    <tr>
    <td></td>
    <td>Mid-Day</td>
      <td>$\$10 K$</td>
      <td>$180 K$</td>
  </tr>
              <tr>
    <td></td>
    <td>Evening</td>
      <td>$\$60 K$</td>
      <td>$810 K$</td>
  </tr>
  <tr>
    <td>Radio</td>
    <td>Morning</td>
      <td>$\$15 K$</td>
      <td>$180 K$</td>
  </tr>
    <tr>
    <td></td>
    <td>Mid-Day</td>
      <td>$\$15 K$</td>
      <td>$17 K$</td>
  </tr>
              <tr>
    <td></td>
    <td>Evening</td>
      <td>$\$10 K$</td>
      <td>$16 K$</td>
  </tr>
            </table></li>
        <br>
        <li>There exists restrictions on the advertising plan that SALS can craft for their client.</li>
        <br>
        <ul>
            <li>The client corporation has budgeted $\$800,000$ for the campaign.</li>
            <br>
            <li>To restrict overexposure to any particular audience, the client wants no more than $\$300,000$ put into any one category (Magazine, Newspapers, Television, Radio).</li>
            <br>
            <li>Additionally, to ensure a broad range of exposure, at least $\$100,000$ must be spent in each category.</li>
            <br>
            <li>Finally, there has to be an integer number of units purchased of each kind of advertisement, as no fractional units are allowed.</li>
            <br>
        </ul>
        <li style="color:red">Formulate an optimization problem to determine the optimal advertising plan for the client, and use CVXPY to estimate the optimal advertising plan.</li>
        <br>
        <li style="color:red"><i>Hint: you might need to install a package <b>! pip install cvxopt</b> (some operating systems require you to restart your computer after installation), then change the solver method to <b>prob.solve(solver='GLPK_MI')</b>.</li>
        <br>
    </ul>
</font>

<h3>Decision Variables</h3>
<br>
<font size="+1">
    <ul>
        <li>What are the decision variables?</li>
        <br>
    </ul>
</font>

Describe them in Markdown, you don't have to use LaTeX, but it is good practice!

$$\begin{align} 
& \text{The decision variables are set of the number of units purchased for every sub-category advertisement, } \\ 
& \text{and there are 11 of them in total.} 
\end{align}
$$  

In [27]:
# initiating the varaibles as integers as required by the constraint

Magazines = cp.Variable(3, integer=True)

Newspapers = cp.Variable(2, integer=True)

Television = cp.Variable(3, integer=True)

Radio = cp.Variable(3, integer=True)

<h3>Objective</h3>
<br>
<font size="+1">
    <ul>
        <li>What is the objective and the associated objective function?</li>
        <br>
    </ul>
</font>

Describe them in Markdown, you don't have to use LaTeX, but it is good practice!

$$\begin{align} 
& \text{The the objective is maximizing the possible exposure rating,} \\  \\
& \text{i.e. maximize: } 15,000 \cdot Magazines_{Literary} + 22,500 \cdot Magazines_{News} + 24,000 \cdot Magazines_{Topical} \\
& + 37,500 \cdot Newspapers_{Morning} + 75,000 \cdot Newspapers_{Evening}  \\
& + 275,000 \cdot Television_{Morning}+180,000 \cdot Television_{Mid-day}+810,000 \cdot Television_{Evening} \\
& +180,000 \cdot Radio_{Morning}+17,000 \cdot Radio_{Mid-day}+16,000 \cdot Radio_{Evening} \\ \\
& \text{The objective function is written in Python code below.} 
\end{align}
$$  

In [28]:
# define the objective function

g = (15_000*Magazines[0] + 22_500*Magazines[1] + 24_000*Magazines[2] 
     + 37_500*Newspapers[0] + 75_000*Newspapers[1] 
     +275_000* Television[0]+180_000* Television[1]+810_000* Television[2]
     +180_000*Radio[0]+17_000*Radio[1]+16_000*Radio[2]
    )

objective = cp.Maximize(g)

<h3>Constraints</h3>
<br>
<font size="+1">
    <ul>
        <li>What are the constraints imposed by the client?</li>
        <br>
    </ul>
</font>

Describe them in Markdown, you don't have to use LaTeX, but it is good practice!

$$\begin{align} 
& \text{The constraints are the following:} \\ 
& \text{Constraint 1. The total budget of the entire campagin is 800,000 dollars.} \\
& \text{Constraint 2. The total money spent on any of the 4 categroies must not exceed 300,000 dollars.} \\
& \text{Constraint 3. The total money spent on any of the 4 categroies must be at least 100,000 dollars. } \\
& \text{Constraint 4. The number of units purchased for any of the 4 categroies must be an integer  } \\
& \text{(satisfied when the variables are initiated).} \\
& \text{Constraint 5. The number of units purchased for any of the sub-categroies must be greater than or euqal to 0.  } \\
\end{align}
$$  

In [29]:
# define the constraints

constraint_1 = (7_500*Magazines[0] + 10_000*Magazines[1]+15_000*Magazines[2]+
               2_000*Newspapers[0]+3_000*Newspapers[1]+
               20_000*Television[0]+10_000*Television[1]+60_000*Television[2]+
               15_000*Radio[0]+15_000*Radio[1]+10_000*Radio[2] <= 800_000)

constraint_2_1 = (7_500*Magazines[0] + 10_000*Magazines[1]+15_000*Magazines[2] <= 300_000)
constraint_2_2 = (2_000*Newspapers[0]+3_000*Newspapers[1] <= 300_000)
constraint_2_3 = (20_000*Television[0]+10_000*Television[1]+60_000*Television[2] <= 300_000)
constraint_2_4 = (15_000*Radio[0]+15_000*Radio[1]+10_000*Radio[2] <= 300_000)

constraint_3_1 = (7_500*Magazines[0] + 10_000*Magazines[1]+15_000*Magazines[2] >= 100_000)
constraint_3_2 = (2_000*Newspapers[0]+3_000*Newspapers[1] >= 100_000)
constraint_3_3 = (20_000*Television[0]+10_000*Television[1]+60_000*Television[2]  >= 100_000)
constraint_3_4 = (15_000*Radio[0]+15_000*Radio[1]+10_000*Radio[2] >= 100_000)

constraint_4_1 = (Magazines>=0)
constraint_4_2 = (Newspapers>=0)
constraint_4_3 = (Television>=0)
constraint_4_4 = (Radio>=0)

<h3>Solution</h3>
<br>
<font size="+1">
    <ul>
        <li>What is the solution to the problem?</li>
        <br>
        <li>How can you interpret the solution?</li>
        <br>
    </ul>
</font>

In [30]:
prob = cp.Problem(objective, [constraint_1, 
                              constraint_2_1, constraint_2_2, constraint_2_3, constraint_2_4,
                             constraint_3_1, constraint_3_2, constraint_3_3, constraint_3_4,
                             constraint_4_1, constraint_4_2, constraint_4_3, constraint_4_4])

In [31]:
prob.solve(solver='GLPK_MI')

14235000.0

In [32]:
print(Magazines.value)

print(Newspapers.value)

print(Television.value)

print(Radio.value)

[ 0. 10.  0.]
[ 0. 98.]
[ 0. 30.  0.]
[7. 0. 0.]


$$\begin{align} 
& \text{Interpretation: in order to produce the maximal value of  the exposure rating, which is 14,235,000, the} \\ 
& \text{client should purchase 10 units of Magazine News ads, 98 units of Evening Newspaper ads, 30 units of} \\
& \text{Mid-day Television ads, and 7 units of Morning Radio ads.} \\
\end{align}
$$  